apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
  creationTimestamp: "2024-11-16T01:35:58Z"
  generation: 5
  labels:
    app: med-paciente-ms
  name: med-paciente-ms
  namespace: default
  resourceVersion: "62603"
  uid: 96b4596b-8449-4734-a3e7-c26f28b77848
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: med-paciente-ms
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: med-paciente-ms
    spec:
      containers:
      - env:
        - name: DB_USER
          value: isbn
        - name: DB_PASSWORD
          value: byhiu578m
        - name: DB_HOST
          value: 34.48.138.11
        - name: DB_NAME
          value: med-users-db
        image: us-east4-docker.pkg.dev/cbse-2024ii-438404/telemed/med-paciente-ms
        imagePullPolicy: Always
        name: med-paciente-ms
        ports:
        - containerPort: 4000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30