apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2024-11-16T01:37:05Z"
  generation: 2
  labels:
    app: unal-telemed-ag
  name: unal-telemed-ag
  namespace: default
  resourceVersion: "66570"
  uid: 244e0ad9-d57c-4635-bf93-694b14b25e69
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: unal-telemed-ag
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: unal-telemed-ag
    spec:
      containers:
      - env:
        - name: ISBN_USERS_MS_API_URL
          value: http://35.230.188.89:4000
        - name: ISBN_TASKS_MS_API_URL
          value: https://citas-medicas-ms-222710232023.us-east4.run.app
        image: us-east4-docker.pkg.dev/cbse-2024ii-438404/telemed/unal-telemed-ag
        imagePullPolicy: Always
        name: unal-telemed-ag
        ports:
        - containerPort: 4500
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30